# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ratracer.protos import ratracer_pb2 as ratracer_dot_protos_dot_ratracer__pb2


class RATracerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeConnection = channel.unary_unary(
                '/RATracer/InitializeConnection',
                request_serializer=ratracer_dot_protos_dot_ratracer__pb2.InitializeConnectionReq.SerializeToString,
                response_deserializer=ratracer_dot_protos_dot_ratracer__pb2.InitializeConnectionResp.FromString,
                )
        self.DeleteConnection = channel.unary_unary(
                '/RATracer/DeleteConnection',
                request_serializer=ratracer_dot_protos_dot_ratracer__pb2.DeleteConnectionReq.SerializeToString,
                response_deserializer=ratracer_dot_protos_dot_ratracer__pb2.DeleteConnectionResp.FromString,
                )
        self.StaticMethod = channel.unary_unary(
                '/RATracer/StaticMethod',
                request_serializer=ratracer_dot_protos_dot_ratracer__pb2.StaticMethodReq.SerializeToString,
                response_deserializer=ratracer_dot_protos_dot_ratracer__pb2.StaticMethodResp.FromString,
                )
        self.StaticGetter = channel.unary_unary(
                '/RATracer/StaticGetter',
                request_serializer=ratracer_dot_protos_dot_ratracer__pb2.StaticGetterReq.SerializeToString,
                response_deserializer=ratracer_dot_protos_dot_ratracer__pb2.StaticGetterResp.FromString,
                )
        self.StaticSetter = channel.unary_unary(
                '/RATracer/StaticSetter',
                request_serializer=ratracer_dot_protos_dot_ratracer__pb2.StaticSetterReq.SerializeToString,
                response_deserializer=ratracer_dot_protos_dot_ratracer__pb2.StaticSetterResp.FromString,
                )
        self.Initialize = channel.unary_unary(
                '/RATracer/Initialize',
                request_serializer=ratracer_dot_protos_dot_ratracer__pb2.InitializeReq.SerializeToString,
                response_deserializer=ratracer_dot_protos_dot_ratracer__pb2.InitializeResp.FromString,
                )
        self.Uninitialize = channel.unary_unary(
                '/RATracer/Uninitialize',
                request_serializer=ratracer_dot_protos_dot_ratracer__pb2.UninitializeReq.SerializeToString,
                response_deserializer=ratracer_dot_protos_dot_ratracer__pb2.UninitializeResp.FromString,
                )
        self.GenericGetter = channel.unary_unary(
                '/RATracer/GenericGetter',
                request_serializer=ratracer_dot_protos_dot_ratracer__pb2.GenericGetterReq.SerializeToString,
                response_deserializer=ratracer_dot_protos_dot_ratracer__pb2.GenericGetterResp.FromString,
                )
        self.GenericSetter = channel.unary_unary(
                '/RATracer/GenericSetter',
                request_serializer=ratracer_dot_protos_dot_ratracer__pb2.GenericSetterReq.SerializeToString,
                response_deserializer=ratracer_dot_protos_dot_ratracer__pb2.GenericSetterResp.FromString,
                )
        self.GenericMethod = channel.unary_unary(
                '/RATracer/GenericMethod',
                request_serializer=ratracer_dot_protos_dot_ratracer__pb2.GenericMethodReq.SerializeToString,
                response_deserializer=ratracer_dot_protos_dot_ratracer__pb2.GenericMethodResp.FromString,
                )
        self.BatchedTrace = channel.unary_unary(
                '/RATracer/BatchedTrace',
                request_serializer=ratracer_dot_protos_dot_ratracer__pb2.BatchedTraceMsg.SerializeToString,
                response_deserializer=ratracer_dot_protos_dot_ratracer__pb2.EmptyMsg.FromString,
                )


class RATracerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitializeConnection(self, request, context):
        """Used when the client-server connection starts
        i.e., when the RATracerClientHelper class is initialized
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteConnection(self, request, context):
        """Used when the client-server connection stops
        i.e., when the RATracerClientHelper class is deleted
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StaticMethod(self, request, context):
        """Used for all static and class methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StaticGetter(self, request, context):
        """Used for all static and class variable read access
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StaticSetter(self, request, context):
        """Used for all static and class variable write access
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Initialize(self, request, context):
        """Used for the __init__ method
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Uninitialize(self, request, context):
        """Used for the __del__ method
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenericGetter(self, request, context):
        """Used for property getters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenericSetter(self, request, context):
        """Used for property setters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenericMethod(self, request, context):
        """Used for the remaining methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchedTrace(self, request, context):
        """Used for sending traces (can be a batch or a single trace)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RATracerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializeConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeConnection,
                    request_deserializer=ratracer_dot_protos_dot_ratracer__pb2.InitializeConnectionReq.FromString,
                    response_serializer=ratracer_dot_protos_dot_ratracer__pb2.InitializeConnectionResp.SerializeToString,
            ),
            'DeleteConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteConnection,
                    request_deserializer=ratracer_dot_protos_dot_ratracer__pb2.DeleteConnectionReq.FromString,
                    response_serializer=ratracer_dot_protos_dot_ratracer__pb2.DeleteConnectionResp.SerializeToString,
            ),
            'StaticMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.StaticMethod,
                    request_deserializer=ratracer_dot_protos_dot_ratracer__pb2.StaticMethodReq.FromString,
                    response_serializer=ratracer_dot_protos_dot_ratracer__pb2.StaticMethodResp.SerializeToString,
            ),
            'StaticGetter': grpc.unary_unary_rpc_method_handler(
                    servicer.StaticGetter,
                    request_deserializer=ratracer_dot_protos_dot_ratracer__pb2.StaticGetterReq.FromString,
                    response_serializer=ratracer_dot_protos_dot_ratracer__pb2.StaticGetterResp.SerializeToString,
            ),
            'StaticSetter': grpc.unary_unary_rpc_method_handler(
                    servicer.StaticSetter,
                    request_deserializer=ratracer_dot_protos_dot_ratracer__pb2.StaticSetterReq.FromString,
                    response_serializer=ratracer_dot_protos_dot_ratracer__pb2.StaticSetterResp.SerializeToString,
            ),
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=ratracer_dot_protos_dot_ratracer__pb2.InitializeReq.FromString,
                    response_serializer=ratracer_dot_protos_dot_ratracer__pb2.InitializeResp.SerializeToString,
            ),
            'Uninitialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Uninitialize,
                    request_deserializer=ratracer_dot_protos_dot_ratracer__pb2.UninitializeReq.FromString,
                    response_serializer=ratracer_dot_protos_dot_ratracer__pb2.UninitializeResp.SerializeToString,
            ),
            'GenericGetter': grpc.unary_unary_rpc_method_handler(
                    servicer.GenericGetter,
                    request_deserializer=ratracer_dot_protos_dot_ratracer__pb2.GenericGetterReq.FromString,
                    response_serializer=ratracer_dot_protos_dot_ratracer__pb2.GenericGetterResp.SerializeToString,
            ),
            'GenericSetter': grpc.unary_unary_rpc_method_handler(
                    servicer.GenericSetter,
                    request_deserializer=ratracer_dot_protos_dot_ratracer__pb2.GenericSetterReq.FromString,
                    response_serializer=ratracer_dot_protos_dot_ratracer__pb2.GenericSetterResp.SerializeToString,
            ),
            'GenericMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.GenericMethod,
                    request_deserializer=ratracer_dot_protos_dot_ratracer__pb2.GenericMethodReq.FromString,
                    response_serializer=ratracer_dot_protos_dot_ratracer__pb2.GenericMethodResp.SerializeToString,
            ),
            'BatchedTrace': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchedTrace,
                    request_deserializer=ratracer_dot_protos_dot_ratracer__pb2.BatchedTraceMsg.FromString,
                    response_serializer=ratracer_dot_protos_dot_ratracer__pb2.EmptyMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RATracer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RATracer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitializeConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RATracer/InitializeConnection',
            ratracer_dot_protos_dot_ratracer__pb2.InitializeConnectionReq.SerializeToString,
            ratracer_dot_protos_dot_ratracer__pb2.InitializeConnectionResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RATracer/DeleteConnection',
            ratracer_dot_protos_dot_ratracer__pb2.DeleteConnectionReq.SerializeToString,
            ratracer_dot_protos_dot_ratracer__pb2.DeleteConnectionResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StaticMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RATracer/StaticMethod',
            ratracer_dot_protos_dot_ratracer__pb2.StaticMethodReq.SerializeToString,
            ratracer_dot_protos_dot_ratracer__pb2.StaticMethodResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StaticGetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RATracer/StaticGetter',
            ratracer_dot_protos_dot_ratracer__pb2.StaticGetterReq.SerializeToString,
            ratracer_dot_protos_dot_ratracer__pb2.StaticGetterResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StaticSetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RATracer/StaticSetter',
            ratracer_dot_protos_dot_ratracer__pb2.StaticSetterReq.SerializeToString,
            ratracer_dot_protos_dot_ratracer__pb2.StaticSetterResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RATracer/Initialize',
            ratracer_dot_protos_dot_ratracer__pb2.InitializeReq.SerializeToString,
            ratracer_dot_protos_dot_ratracer__pb2.InitializeResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Uninitialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RATracer/Uninitialize',
            ratracer_dot_protos_dot_ratracer__pb2.UninitializeReq.SerializeToString,
            ratracer_dot_protos_dot_ratracer__pb2.UninitializeResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenericGetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RATracer/GenericGetter',
            ratracer_dot_protos_dot_ratracer__pb2.GenericGetterReq.SerializeToString,
            ratracer_dot_protos_dot_ratracer__pb2.GenericGetterResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenericSetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RATracer/GenericSetter',
            ratracer_dot_protos_dot_ratracer__pb2.GenericSetterReq.SerializeToString,
            ratracer_dot_protos_dot_ratracer__pb2.GenericSetterResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenericMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RATracer/GenericMethod',
            ratracer_dot_protos_dot_ratracer__pb2.GenericMethodReq.SerializeToString,
            ratracer_dot_protos_dot_ratracer__pb2.GenericMethodResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchedTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RATracer/BatchedTrace',
            ratracer_dot_protos_dot_ratracer__pb2.BatchedTraceMsg.SerializeToString,
            ratracer_dot_protos_dot_ratracer__pb2.EmptyMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
