# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from niraapad.protos import niraapad_pb2 as niraapad_dot_protos_dot_niraapad__pb2


class NiraapadStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeConnection = channel.unary_unary(
                '/Niraapad/InitializeConnection',
                request_serializer=niraapad_dot_protos_dot_niraapad__pb2.InitializeConnectionReq.SerializeToString,
                response_deserializer=niraapad_dot_protos_dot_niraapad__pb2.InitializeConnectionResp.FromString,
                )
        self.DeleteConnection = channel.unary_unary(
                '/Niraapad/DeleteConnection',
                request_serializer=niraapad_dot_protos_dot_niraapad__pb2.DeleteConnectionReq.SerializeToString,
                response_deserializer=niraapad_dot_protos_dot_niraapad__pb2.DeleteConnectionResp.FromString,
                )
        self.StaticMethod = channel.unary_unary(
                '/Niraapad/StaticMethod',
                request_serializer=niraapad_dot_protos_dot_niraapad__pb2.StaticMethodReq.SerializeToString,
                response_deserializer=niraapad_dot_protos_dot_niraapad__pb2.StaticMethodResp.FromString,
                )
        self.StaticMethodTrace = channel.unary_unary(
                '/Niraapad/StaticMethodTrace',
                request_serializer=niraapad_dot_protos_dot_niraapad__pb2.StaticMethodTraceMsg.SerializeToString,
                response_deserializer=niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.FromString,
                )
        self.StaticGetter = channel.unary_unary(
                '/Niraapad/StaticGetter',
                request_serializer=niraapad_dot_protos_dot_niraapad__pb2.StaticGetterReq.SerializeToString,
                response_deserializer=niraapad_dot_protos_dot_niraapad__pb2.StaticGetterResp.FromString,
                )
        self.StaticGetterTrace = channel.unary_unary(
                '/Niraapad/StaticGetterTrace',
                request_serializer=niraapad_dot_protos_dot_niraapad__pb2.StaticGetterTraceMsg.SerializeToString,
                response_deserializer=niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.FromString,
                )
        self.StaticSetter = channel.unary_unary(
                '/Niraapad/StaticSetter',
                request_serializer=niraapad_dot_protos_dot_niraapad__pb2.StaticSetterReq.SerializeToString,
                response_deserializer=niraapad_dot_protos_dot_niraapad__pb2.StaticSetterResp.FromString,
                )
        self.StaticSetterTrace = channel.unary_unary(
                '/Niraapad/StaticSetterTrace',
                request_serializer=niraapad_dot_protos_dot_niraapad__pb2.StaticSetterTraceMsg.SerializeToString,
                response_deserializer=niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.FromString,
                )
        self.Initialize = channel.unary_unary(
                '/Niraapad/Initialize',
                request_serializer=niraapad_dot_protos_dot_niraapad__pb2.InitializeReq.SerializeToString,
                response_deserializer=niraapad_dot_protos_dot_niraapad__pb2.InitializeResp.FromString,
                )
        self.InitializeTrace = channel.unary_unary(
                '/Niraapad/InitializeTrace',
                request_serializer=niraapad_dot_protos_dot_niraapad__pb2.InitializeTraceMsg.SerializeToString,
                response_deserializer=niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.FromString,
                )
        self.GenericGetter = channel.unary_unary(
                '/Niraapad/GenericGetter',
                request_serializer=niraapad_dot_protos_dot_niraapad__pb2.GenericGetterReq.SerializeToString,
                response_deserializer=niraapad_dot_protos_dot_niraapad__pb2.GenericGetterResp.FromString,
                )
        self.GenericGetterTrace = channel.unary_unary(
                '/Niraapad/GenericGetterTrace',
                request_serializer=niraapad_dot_protos_dot_niraapad__pb2.GenericGetterTraceMsg.SerializeToString,
                response_deserializer=niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.FromString,
                )
        self.GenericDeviceGetter = channel.unary_unary(
                '/Niraapad/GenericDeviceGetter',
                request_serializer=niraapad_dot_protos_dot_niraapad__pb2.GenericDeviceGetterReq.SerializeToString,
                response_deserializer=niraapad_dot_protos_dot_niraapad__pb2.GenericDeviceGetterResp.FromString,
                )
        self.GenericDeviceGetterTrace = channel.unary_unary(
                '/Niraapad/GenericDeviceGetterTrace',
                request_serializer=niraapad_dot_protos_dot_niraapad__pb2.GenericDeviceGetterTraceMsg.SerializeToString,
                response_deserializer=niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.FromString,
                )
        self.GenericSetter = channel.unary_unary(
                '/Niraapad/GenericSetter',
                request_serializer=niraapad_dot_protos_dot_niraapad__pb2.GenericSetterReq.SerializeToString,
                response_deserializer=niraapad_dot_protos_dot_niraapad__pb2.GenericSetterResp.FromString,
                )
        self.GenericSetterTrace = channel.unary_unary(
                '/Niraapad/GenericSetterTrace',
                request_serializer=niraapad_dot_protos_dot_niraapad__pb2.GenericSetterTraceMsg.SerializeToString,
                response_deserializer=niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.FromString,
                )
        self.GenericMethod = channel.unary_unary(
                '/Niraapad/GenericMethod',
                request_serializer=niraapad_dot_protos_dot_niraapad__pb2.GenericMethodReq.SerializeToString,
                response_deserializer=niraapad_dot_protos_dot_niraapad__pb2.GenericMethodResp.FromString,
                )
        self.GenericMethodTrace = channel.unary_unary(
                '/Niraapad/GenericMethodTrace',
                request_serializer=niraapad_dot_protos_dot_niraapad__pb2.GenericMethodTraceMsg.SerializeToString,
                response_deserializer=niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.FromString,
                )


class NiraapadServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitializeConnection(self, request, context):
        """Used when the client-server connection starts
        i.e., when the NiraapadClientHelper class is initialized
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteConnection(self, request, context):
        """Used when the client-server connection stops
        i.e., when the NiraapadClientHelper class is deleted
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StaticMethod(self, request, context):
        """Used for all static and class methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StaticMethodTrace(self, request, context):
        """Used for all static and class methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StaticGetter(self, request, context):
        """Used for all static and class variable read access
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StaticGetterTrace(self, request, context):
        """Used for all static and class variable read access
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StaticSetter(self, request, context):
        """Used for all static and class variable write access
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StaticSetterTrace(self, request, context):
        """Used for all static and class variable write access
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Initialize(self, request, context):
        """Used for the __init__ method
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitializeTrace(self, request, context):
        """Used for the __init__ method
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenericGetter(self, request, context):
        """Used for property getters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenericGetterTrace(self, request, context):
        """Used for property getters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenericDeviceGetter(self, request, context):
        """Used for specific device property getters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenericDeviceGetterTrace(self, request, context):
        """Used for specific device property getters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenericSetter(self, request, context):
        """Used for property setters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenericSetterTrace(self, request, context):
        """Used for property setters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenericMethod(self, request, context):
        """Used for the remaining methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenericMethodTrace(self, request, context):
        """Used for the remaining methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NiraapadServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializeConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeConnection,
                    request_deserializer=niraapad_dot_protos_dot_niraapad__pb2.InitializeConnectionReq.FromString,
                    response_serializer=niraapad_dot_protos_dot_niraapad__pb2.InitializeConnectionResp.SerializeToString,
            ),
            'DeleteConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteConnection,
                    request_deserializer=niraapad_dot_protos_dot_niraapad__pb2.DeleteConnectionReq.FromString,
                    response_serializer=niraapad_dot_protos_dot_niraapad__pb2.DeleteConnectionResp.SerializeToString,
            ),
            'StaticMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.StaticMethod,
                    request_deserializer=niraapad_dot_protos_dot_niraapad__pb2.StaticMethodReq.FromString,
                    response_serializer=niraapad_dot_protos_dot_niraapad__pb2.StaticMethodResp.SerializeToString,
            ),
            'StaticMethodTrace': grpc.unary_unary_rpc_method_handler(
                    servicer.StaticMethodTrace,
                    request_deserializer=niraapad_dot_protos_dot_niraapad__pb2.StaticMethodTraceMsg.FromString,
                    response_serializer=niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.SerializeToString,
            ),
            'StaticGetter': grpc.unary_unary_rpc_method_handler(
                    servicer.StaticGetter,
                    request_deserializer=niraapad_dot_protos_dot_niraapad__pb2.StaticGetterReq.FromString,
                    response_serializer=niraapad_dot_protos_dot_niraapad__pb2.StaticGetterResp.SerializeToString,
            ),
            'StaticGetterTrace': grpc.unary_unary_rpc_method_handler(
                    servicer.StaticGetterTrace,
                    request_deserializer=niraapad_dot_protos_dot_niraapad__pb2.StaticGetterTraceMsg.FromString,
                    response_serializer=niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.SerializeToString,
            ),
            'StaticSetter': grpc.unary_unary_rpc_method_handler(
                    servicer.StaticSetter,
                    request_deserializer=niraapad_dot_protos_dot_niraapad__pb2.StaticSetterReq.FromString,
                    response_serializer=niraapad_dot_protos_dot_niraapad__pb2.StaticSetterResp.SerializeToString,
            ),
            'StaticSetterTrace': grpc.unary_unary_rpc_method_handler(
                    servicer.StaticSetterTrace,
                    request_deserializer=niraapad_dot_protos_dot_niraapad__pb2.StaticSetterTraceMsg.FromString,
                    response_serializer=niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.SerializeToString,
            ),
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=niraapad_dot_protos_dot_niraapad__pb2.InitializeReq.FromString,
                    response_serializer=niraapad_dot_protos_dot_niraapad__pb2.InitializeResp.SerializeToString,
            ),
            'InitializeTrace': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeTrace,
                    request_deserializer=niraapad_dot_protos_dot_niraapad__pb2.InitializeTraceMsg.FromString,
                    response_serializer=niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.SerializeToString,
            ),
            'GenericGetter': grpc.unary_unary_rpc_method_handler(
                    servicer.GenericGetter,
                    request_deserializer=niraapad_dot_protos_dot_niraapad__pb2.GenericGetterReq.FromString,
                    response_serializer=niraapad_dot_protos_dot_niraapad__pb2.GenericGetterResp.SerializeToString,
            ),
            'GenericGetterTrace': grpc.unary_unary_rpc_method_handler(
                    servicer.GenericGetterTrace,
                    request_deserializer=niraapad_dot_protos_dot_niraapad__pb2.GenericGetterTraceMsg.FromString,
                    response_serializer=niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.SerializeToString,
            ),
            'GenericDeviceGetter': grpc.unary_unary_rpc_method_handler(
                    servicer.GenericDeviceGetter,
                    request_deserializer=niraapad_dot_protos_dot_niraapad__pb2.GenericDeviceGetterReq.FromString,
                    response_serializer=niraapad_dot_protos_dot_niraapad__pb2.GenericDeviceGetterResp.SerializeToString,
            ),
            'GenericDeviceGetterTrace': grpc.unary_unary_rpc_method_handler(
                    servicer.GenericDeviceGetterTrace,
                    request_deserializer=niraapad_dot_protos_dot_niraapad__pb2.GenericDeviceGetterTraceMsg.FromString,
                    response_serializer=niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.SerializeToString,
            ),
            'GenericSetter': grpc.unary_unary_rpc_method_handler(
                    servicer.GenericSetter,
                    request_deserializer=niraapad_dot_protos_dot_niraapad__pb2.GenericSetterReq.FromString,
                    response_serializer=niraapad_dot_protos_dot_niraapad__pb2.GenericSetterResp.SerializeToString,
            ),
            'GenericSetterTrace': grpc.unary_unary_rpc_method_handler(
                    servicer.GenericSetterTrace,
                    request_deserializer=niraapad_dot_protos_dot_niraapad__pb2.GenericSetterTraceMsg.FromString,
                    response_serializer=niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.SerializeToString,
            ),
            'GenericMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.GenericMethod,
                    request_deserializer=niraapad_dot_protos_dot_niraapad__pb2.GenericMethodReq.FromString,
                    response_serializer=niraapad_dot_protos_dot_niraapad__pb2.GenericMethodResp.SerializeToString,
            ),
            'GenericMethodTrace': grpc.unary_unary_rpc_method_handler(
                    servicer.GenericMethodTrace,
                    request_deserializer=niraapad_dot_protos_dot_niraapad__pb2.GenericMethodTraceMsg.FromString,
                    response_serializer=niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Niraapad', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Niraapad(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitializeConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Niraapad/InitializeConnection',
            niraapad_dot_protos_dot_niraapad__pb2.InitializeConnectionReq.SerializeToString,
            niraapad_dot_protos_dot_niraapad__pb2.InitializeConnectionResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Niraapad/DeleteConnection',
            niraapad_dot_protos_dot_niraapad__pb2.DeleteConnectionReq.SerializeToString,
            niraapad_dot_protos_dot_niraapad__pb2.DeleteConnectionResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StaticMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Niraapad/StaticMethod',
            niraapad_dot_protos_dot_niraapad__pb2.StaticMethodReq.SerializeToString,
            niraapad_dot_protos_dot_niraapad__pb2.StaticMethodResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StaticMethodTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Niraapad/StaticMethodTrace',
            niraapad_dot_protos_dot_niraapad__pb2.StaticMethodTraceMsg.SerializeToString,
            niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StaticGetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Niraapad/StaticGetter',
            niraapad_dot_protos_dot_niraapad__pb2.StaticGetterReq.SerializeToString,
            niraapad_dot_protos_dot_niraapad__pb2.StaticGetterResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StaticGetterTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Niraapad/StaticGetterTrace',
            niraapad_dot_protos_dot_niraapad__pb2.StaticGetterTraceMsg.SerializeToString,
            niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StaticSetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Niraapad/StaticSetter',
            niraapad_dot_protos_dot_niraapad__pb2.StaticSetterReq.SerializeToString,
            niraapad_dot_protos_dot_niraapad__pb2.StaticSetterResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StaticSetterTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Niraapad/StaticSetterTrace',
            niraapad_dot_protos_dot_niraapad__pb2.StaticSetterTraceMsg.SerializeToString,
            niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Niraapad/Initialize',
            niraapad_dot_protos_dot_niraapad__pb2.InitializeReq.SerializeToString,
            niraapad_dot_protos_dot_niraapad__pb2.InitializeResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitializeTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Niraapad/InitializeTrace',
            niraapad_dot_protos_dot_niraapad__pb2.InitializeTraceMsg.SerializeToString,
            niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenericGetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Niraapad/GenericGetter',
            niraapad_dot_protos_dot_niraapad__pb2.GenericGetterReq.SerializeToString,
            niraapad_dot_protos_dot_niraapad__pb2.GenericGetterResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenericGetterTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Niraapad/GenericGetterTrace',
            niraapad_dot_protos_dot_niraapad__pb2.GenericGetterTraceMsg.SerializeToString,
            niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenericDeviceGetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Niraapad/GenericDeviceGetter',
            niraapad_dot_protos_dot_niraapad__pb2.GenericDeviceGetterReq.SerializeToString,
            niraapad_dot_protos_dot_niraapad__pb2.GenericDeviceGetterResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenericDeviceGetterTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Niraapad/GenericDeviceGetterTrace',
            niraapad_dot_protos_dot_niraapad__pb2.GenericDeviceGetterTraceMsg.SerializeToString,
            niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenericSetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Niraapad/GenericSetter',
            niraapad_dot_protos_dot_niraapad__pb2.GenericSetterReq.SerializeToString,
            niraapad_dot_protos_dot_niraapad__pb2.GenericSetterResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenericSetterTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Niraapad/GenericSetterTrace',
            niraapad_dot_protos_dot_niraapad__pb2.GenericSetterTraceMsg.SerializeToString,
            niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenericMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Niraapad/GenericMethod',
            niraapad_dot_protos_dot_niraapad__pb2.GenericMethodReq.SerializeToString,
            niraapad_dot_protos_dot_niraapad__pb2.GenericMethodResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenericMethodTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Niraapad/GenericMethodTrace',
            niraapad_dot_protos_dot_niraapad__pb2.GenericMethodTraceMsg.SerializeToString,
            niraapad_dot_protos_dot_niraapad__pb2.EmptyMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
